import "../styles/globals.css";
import "react-toastify/dist/ReactToastify.css";
import styles from "../styles/Home.module.css";
import { CssBaseline } from "@mui/material";
import { getLibrary } from "src/utils/connectors";
import { Web3ReactProvider } from "@web3-react/core";
import type { AppProps } from "next/app";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import HomeIcon from "@mui/icons-material/Home";
import ChairIcon from "@mui/icons-material/Chair";
import LocalMallIcon from "@mui/icons-material/LocalMall";
import { ToastContainer } from "react-toastify";
import ConnectWalletButton from "src/components/connectWalletButton";
import Loyality from "src/components/loyalityPoints";

const darkTheme = createTheme({
  palette: {
    mode: "dark",
  },
} as any);

export default function App({ Component, pageProps }: AppProps) {
  return (
    <Web3ReactProvider getLibrary={getLibrary}>
      <ThemeProvider theme={darkTheme}>
        <CssBaseline />
        <div className={styles.container}>
          <Head>
            <title>Furniture Shop</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <nav className={styles.navbar}>
            <Link href="/" className={styles.navbarItem}>
              <span className={styles.logo}>
                <HomeIcon />
              </span>
            </Link>
            <Link href="/products" className={styles.navbarItem}>
              <span className={styles.logo}>
                <ChairIcon />
              </span>
            </Link>
            <Link href="/my" className={styles.navbarItem}>
              <span className={styles.logo}>
                <LocalMallIcon />
              </span>
            </Link>
            <div
              style={{
                justifyContent: "flex-end",
                display: "flex",
                alignItems: "center",
                flex: 1,
              }}
            >
              <Loyality />
              <ConnectWalletButton />
            </div>
          </nav>

          <main className={styles.main}>
            <Component {...pageProps} />
          </main>

          <footer className={styles.footer}>
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </footer>
        </div>

        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
        />
      </ThemeProvider>
    </Web3ReactProvider>
  );
}
